// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSsocB8vMnFd4d13moCQBmKqB9wEtjfvY',
    appId: '1:443981257323:web:845ec22c4774094264af2e',
    messagingSenderId: '443981257323',
    projectId: 'om-event',
    authDomain: 'om-event.firebaseapp.com',
    databaseURL: 'https://om-event-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'om-event.firebasestorage.app',
    measurementId: 'G-RTEJQ1HFKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFpKAUXwIDnoQBrt5Id-xJjn-h5WVv1pc',
    appId: '1:443981257323:android:a99b824ca6d4a10b64af2e',
    messagingSenderId: '443981257323',
    projectId: 'om-event',
    databaseURL: 'https://om-event-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'om-event.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJp_QPbfh24tfr37bYX3Gpt46fT-zmQE',
    appId: '1:443981257323:ios:78a69a78355ddd9b64af2e',
    messagingSenderId: '443981257323',
    projectId: 'om-event',
    databaseURL: 'https://om-event-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'om-event.firebasestorage.app',
    androidClientId: '443981257323-u5kcr8uep26urtj4olbsv8lgfnq7v31n.apps.googleusercontent.com',
    iosClientId: '443981257323-3c774roa0hhuq8abeipte96fmq4gu7od.apps.googleusercontent.com',
    iosBundleId: 'com.omevents.omEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJp_QPbfh24tfr37bYX3Gpt46fT-zmQE',
    appId: '1:443981257323:ios:78a69a78355ddd9b64af2e',
    messagingSenderId: '443981257323',
    projectId: 'om-event',
    databaseURL: 'https://om-event-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'om-event.firebasestorage.app',
    androidClientId: '443981257323-u5kcr8uep26urtj4olbsv8lgfnq7v31n.apps.googleusercontent.com',
    iosClientId: '443981257323-3c774roa0hhuq8abeipte96fmq4gu7od.apps.googleusercontent.com',
    iosBundleId: 'com.omevents.omEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSsocB8vMnFd4d13moCQBmKqB9wEtjfvY',
    appId: '1:443981257323:web:5732633aed5100e664af2e',
    messagingSenderId: '443981257323',
    projectId: 'om-event',
    authDomain: 'om-event.firebaseapp.com',
    databaseURL: 'https://om-event-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'om-event.firebasestorage.app',
    measurementId: 'G-EKKXBTVFRX',
  );
}
