import 'package:get/get.dart';
import '../../core/errors/failures.dart';
import '../../core/utils/validators.dart';
import '../../domain/entities/category.dart';
import '../../domain/entities/experience.dart';
import '../../domain/entities/lead.dart';
import '../../domain/entities/review.dart';
import '../../domain/usecases/get_categories.dart';
import '../../domain/usecases/get_experiences.dart';
import '../../domain/usecases/submit_lead.dart';

class CatalogController extends GetxController {
  final GetCategories getCategories;
  final GetExperiences getExperiences;
  final SubmitLead submitLead;

  CatalogController({
    required this.getCategories,
    required this.getExperiences,
    required this.submitLead,
  });

  // State Observables
  final rxCategories = <Category>[].obs;
  final rxExperiences = <Experience>[].obs;
  final rxReviews = <Review>[].obs;

  final isLoadingCategories = false.obs;
  final isLoadingExperiences = false.obs;
  final isSubmittingLead = false.obs;

  // Search & Filter state
  final selectedCategorySlug = ''.obs;
  final searchQuery = ''.obs;
  final sortBy = 'popular'.obs;

  @override
  void onInit() {
    super.onInit();
    refreshCatalog();

    // Debounce search query changes to avoid database reads on every single keystroke
    debounce(
      searchQuery,
      (_) => loadExperiences(),
      time: const Duration(milliseconds: 500),
    );
  }

  Future<void> refreshCatalog() async {
    await loadCategories();
    await loadExperiences();
  }

  Future<void> loadCategories() async {
    try {
      isLoadingCategories.value = true;
      final results = await getCategories();
      rxCategories.assignAll(results);
    } catch (e) {
      Get.snackbar("Error", e.toString());
    } finally {
      isLoadingCategories.value = false;
    }
  }

  Future<void> loadExperiences() async {
    try {
      isLoadingExperiences.value = true;
      final results = await getExperiences(
        categorySlug:
            selectedCategorySlug.value.isEmpty
                ? null
                : selectedCategorySlug.value,
        searchQuery: searchQuery.value.isEmpty ? null : searchQuery.value,
        sortBy: sortBy.value,
      );
      rxExperiences.assignAll(results);
    } catch (e) {
      Get.snackbar("Error", e.toString());
    } finally {
      isLoadingExperiences.value = false;
    }
  }

  void selectCategory(String slug) {
    if (selectedCategorySlug.value == slug) {
      selectedCategorySlug.value = ''; // Toggle / Clear filter
    } else {
      selectedCategorySlug.value = slug;
    }
    loadExperiences();
  }

  void updateSearchQuery(String query) {
    searchQuery.value = query;
  }

  void updateSort(String option) {
    sortBy.value = option;
    loadExperiences();
  }

  // Submit Callback Inquiry Form (Lead)
  Future<bool> requestCallback({
    required String name,
    required String phone,
    required String dateStr,
    required String budgetStr,
    required String requirements,
  }) async {
    if (!AppValidators.isValidName(name)) {
      Get.snackbar(
        "Validation Error",
        "Please enter a valid name (at least 2 letters).",
      );
      return false;
    }
    if (!AppValidators.isValidPhone(phone)) {
      Get.snackbar(
        "Validation Error",
        "Please enter a valid 10-digit phone number.",
      );
      return false;
    }

    try {
      isSubmittingLead.value = true;
      final cleanedPhone = AppValidators.cleanPhone(phone);
      final budget = double.tryParse(budgetStr) ?? 0.0;
      final eventDate = DateTime.tryParse(dateStr);

      final lead = Lead(
        id: '', // Generated by database
        name: name.trim(),
        phone: cleanedPhone,
        email: '',
        requestType: 'callback',
        eventDate: eventDate,
        budget: budget > 0 ? budget : null,
        requirements: requirements.trim(),
        status: 'new',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await submitLead(lead);
      Get.snackbar(
        "Inquiry Received",
        "Thank you! Our event manager will call you shortly.",
        snackPosition: SnackPosition.BOTTOM,
      );
      return true;
    } on Failure catch (e) {
      Get.snackbar("Inquiry Failed", e.message);
      return false;
    } catch (e) {
      Get.snackbar("Inquiry Failed", e.toString());
      return false;
    } finally {
      isSubmittingLead.value = false;
    }
  }
}
